language: java
services:
  - elasticsearch
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb && sudo dpkg -i --force-confnew elasticsearch-6.0.0.deb && sudo service elasticsearch restart
  - sleep 15
install: mvn install -DskipTests=true -Dgpg.skip=true
after_success:
  - bash <(curl -s https://codecov.io/bash)
